<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <Antlr4 Include="..\..\..\grammar\yagl.g4" Package="EtAlii.Yagl" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Antlr4.Runtime.Standard" />
        <PackageReference Include="Antlr4BuildTasks">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
